// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-sHFem-qg4yr_2NjCi3WYO_l9BEGD8Y',
    appId: '1:265934207111:web:d1a0b714dedb4ee174a022',
    messagingSenderId: '265934207111',
    projectId: 'clotex-86e23',
    authDomain: 'clotex-86e23.firebaseapp.com',
    storageBucket: 'clotex-86e23.firebasestorage.app',
    measurementId: 'G-32MPYRR3P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvm74eGvxQm7pddB0kw4zSvrDnKI793Eo',
    appId: '1:265934207111:android:62fcc90f11e017af74a022',
    messagingSenderId: '265934207111',
    projectId: 'clotex-86e23',
    storageBucket: 'clotex-86e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0Z-cEKMh3fOR0M13Slc-y16XEOCjP5M',
    appId: '1:265934207111:ios:fdc7f12d7e386c6d74a022',
    messagingSenderId: '265934207111',
    projectId: 'clotex-86e23',
    storageBucket: 'clotex-86e23.firebasestorage.app',
    iosBundleId: 'com.example.clotex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC-sHFem-qg4yr_2NjCi3WYO_l9BEGD8Y',
    appId: '1:265934207111:web:aca61246bcf22e5f74a022',
    messagingSenderId: '265934207111',
    projectId: 'clotex-86e23',
    authDomain: 'clotex-86e23.firebaseapp.com',
    storageBucket: 'clotex-86e23.firebasestorage.app',
    measurementId: 'G-H067ZNBE3E',
  );

}